HexChronicle/Fwibble

- client/app/gameview/gameview.jsx
- client/index.html
- server/index.js
> basic react gameview

- .babelrc
- .gitignore
- Modules/Game.js
- Modules/Index.js
- Modules/Signin.js
- client/app/gameview/gameview.js
- client/index.html
- package.json
- server/App.js
- server/_index.js
- webpack.config.js
> React router

- .travis.yml
- package.json
Also added api-history fallback to allow page refresh
closes #18
> Add travis

- Modules/Index.js
- client/components/GameView.js
- client/components/StoryBox.js
- client/components/StoryInput.js
- client/components/StoryTitle.js
- server/App.js
- webpack.config.js
minor fix: typo in webpack.config
> Added exports to child components

- webpack.config.js
> fixes webpack.config typo

- .babelrc
- .gitignore
- webpack.config.js
- changed webpack 'loader' to 'loaders'
- removed presets from babel querystring, added es2015 to .babelrc
- added npm-debug to .gitignore
> webpack and babel bugfixes

- app/actions/texts.js
- test/app/actions/rooms_test.js
closes #13 so to speak
tests seem to pass regardless of requirements...
> some rooms_test

- app/actions/rooms.js
- app/actions/texts.js
- app/actions/users.js
- db/fwibble.sql
- package.json
- test/app/actions/rooms_test.js
- test/app/actions/texts_test.js
- test/app/actions/users_test.js
- test/server/index_test.js
- test/test-helper.js
Tests are not functioning properly and will need additional time.  Appears majority of models are querying correctly.
> Closes #36

- app/actions/rooms.js
- app/actions/texts.js
- app/actions/users.js
- db/db_setup.js
- db/fwibble.sql
- test/app/actions/texts_test.js
- test/test-helper.js
> Bugfix Model and Testing fixes

- app/components/signin/Signin.js
> signin basics

- app/actions/games.js
- db/fwibble.sql
- package.json
- test/app/actions/games_test.js
Package.json altered with addition of sha1
> Closes #100

- app/components/gameview/GameView.js
- server/socket.js
- views/index.html
> Rebased state

- app/components/gameview/StoryInput.js
> 6 word validation in place

- app/actions/users.js
- package.json
- test/app/actions/users_test.js
> Backend user auth

- app/actions/sessions.js
- db/fwibble.sql
- package.json
- test/app/actions/sessions_test.js
Added cookie parser to package.json, could be merge conflict
> Sessions backend

- app/components/signin/Signin.js
- server/App.js
- server/auth.js
> Redirect on valid auth

- app/actions/users.js
- server/apis/user-api.js
> findIdByUsername returns false if not found. api reflects this.

- app/actions/users.js
- app/components/gameview/GameView.js
- server/apis/user-api.js
> Password validation now takes username instead of UID

- app/components/signin/Signin.js
- server/App.js
- server/apis/user-api.js
> Signup/signout adds/removes gamehash

- app/actions/games.js
Very small PR to fix games test
> Fixed games model

- app/components/gameview/StoryInput.js
> Closes #201

- app/components/gameview/Fwib.js
- app/components/gameview/GameView.js
- app/components/gameview/StoryBox.js
- app/components/gameview/StoryContainer.js
- app/components/gameview/UsersInRoom.js
> inline fwibs
